export declare function wait(ms: number): Promise<void>;
export declare function maintainAsyncJob(jobExecuter: () => Promise<void>, restartDelay: number): Promise<void>;
export declare function uuid(): `${string}-${string}-${string}-${string}-${string}`;
/**
 * Extracts the creation timestamp from a 63-bit ID generated by the database's
 * `generate_id()` function. Layout: 42-bit ms timestamp | 21-bit random.
 */
export declare function dateFromId(id: bigint | string): Date;
//# sourceMappingURL=index.d.ts.map